server:
  tomcat:
    uri-encoding: UTF-8
  port: 8866

spring:
  http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/

mybatis:
  mapperLocations: classpath*:mapper/*Mapper.xml
  typeAliasesPackage: com.tg.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:config/log-back.xml
  level:
    root: info